### ISSUE TITLE
`AxiosError: Request failed with status code 400`

### ISSUE THREAD

**Issue by tiagobento** [runforesight/workflow-telemetry-action#14]
Hi!

I'm getting an error when running this action on Windows.
Here's the run: https://github.com/tiagobento/kie-tools/actions/runs/2904721533

Please let me know how I can debug it so I can provide more information about the error.

![image](https://user-images.githubusercontent.com/1584568/185967137-baaa02db-cf39-4d04-8734-4a70298d43f5.png)

**Comment by gokhan721** [comment]
Hi Tiago, Thanks for letting this issue. When I tried to produce your error but I couldn't make it. Could you please re-run your workflow by enabling debug option and share our logs? You can do it by following below post if you do not have any idea how to do it. 

https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/

**Comment by serkan-ozal** [comment]
Hi @tiagobento, we have released new version with the fix. Could you please re-run your workflow and check whether the issue has been fixed.

**Comment by tiagobento** [comment]
@serkan-ozal Hi! Just tested it and unfortunately this new version doesn't seem to have fixed the issue :/

See this run:
https://github.com/tiagobento/kie-tools/actions/runs/2934344873

**Comment by gokhan721** [comment]
Hi Tiago, let us check it again! Thanks to inform us.

**Comment by serkan-ozal** [comment]
Hi @tiagobento, There was a missing build issue after actual fix. Could you please retry it again?

**Comment by tiagobento** [comment]
Hey!! Just tested 1.8.2 and it worked fine on Windows! Now I'm getting the same error on macOS 🙈. See https://github.com/tiagobento/kie-tools/actions/runs/2943981565

**Comment by gokhan721** [comment]
Glad to hear that! I have forked your repo to check errors you have. Let me check this out. Then, will inform you. Thanks to report this issue.

**Comment by serkan-ozal** [comment]
Hi @tiagobento,
We have applied another fix for negative stats value. Could you please retry and let us know whether the issue has been fixed with the new version.

**Comment by tiagobento** [comment]
@gokhan721 @serkan-ozal Just tested with `1.8.3` and can confirm that the errors are gone for macOS as well!

Thank you so much for fixing it so fast and congrats for the awesome action! An authentic plug-and-play experience :)

**Comment by serkan-ozal** [comment]
Thanks for quick response @tiagobento. 

Besides that have you checked our CI/CD monitoring product Foresight: https://runforesight.com

If you find our open-source `worklflow-telemetry-action` useful, I think, you may like Foresight too as it has many other additional cool features (detailed process tracing, test result analysis, coverage based change impact analysis, test/workflow rules, etc ...) and it is free for open-source projects.

**Comment by tiagobento** [comment]
Wow, that sounds pretty cool. Glad to hear Foresight is free for open-source projects!  🎉

I'll definitely look into it as soon as I have a chance. 

Keep it up! And thanks again :)

PS: Feel free to close this issue, it's all resolved from my end.
