### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by vasanthdharmaraj** [runforesight/workflow-telemetry-action#18]
What is the Open Source License this project is released?

**Comment by serkan-ozal** [comment]
Hi @vasanthdharmaraj,

We are planning to to release it either Apache 2.0 or MIT?

Could you please describe your use case with this action? Are you planning to use it for your personal works or for your company?

Besides that have you checked our CI/CD monitoring product Foresight: https://runforesight.com

If you find our open-source `worklflow-telemetry-action` useful, I think, you may like Foresight too as it has many other additional cool features (detailed process tracing, test result analysis, coverage based change impact analysis, test/workflow rules, etc ...) and it is free for open-source projects.

**Comment by vasanthdharmaraj** [comment]
Hi, Thanks for the info. We are planning to use it in our company.  We are starting to use GitHub Actions in our enterprise instance. And would like to get the data about disc io, network io and compare it with our existing Jenkins servers' performance. Will take a look at https://www.runforesight.com/ too.

**Comment by serkan-ozal** [comment]
Hi @vasanthdharmaraj, 

`workflow-telemetry-action` is licensed under the `Apache License 2.0`: https://github.com/runforesight/workflow-telemetry-action/blob/master/LICENSE.md 

If you are interested in to learn more about our Github oriented CI monitoring tool `Foresight` (https://www.runforesight.com/), please don't hesitate to pick up a time from my calendar for a quick meeting and product demo: https://calendly.com/serkan-ozal/30min
