### ISSUE TITLE
save-state command is deprecated

### ISSUE THREAD

**Issue by arogic** [runforesight/workflow-telemetry-action#25]
Hi,

we are getting the following Warning in our Github Workflow for action "runforesight/workflow-telemetry-action@v1"

>Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Regards

**Comment by rwxdash** [comment]
Thanks for the report @arogic. 

We are aware of the deprecation and will soon update our action accordingly. Will update this issue once the fix is published.

Bests,
Oguzhan

**Comment by arogic** [comment]
Thanks @rwxdash. Any update on this issue? When can we expect the fix? Regards

**Comment by rwxdash** [comment]
Hey @arogic, it seems like there isn't much for us to do here. We are already using `"@actions/core": "^1.10.0"`, see [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows). I think this is just a warning and not something that breaks the workflows. 

However, we'll follow the package closely to see if the state of this deprecation affects us and upgrade the `@actions/core` package accordingly.

Closing this issue for now.

Bests,
Oguzhan
