### ISSUE TITLE
remove escalation of system command exectution.

### ISSUE THREAD

**Issue by srccn** [runforesight/workflow-telemetry-action#26]
Hi Team:

src/processTrace.ts Line122.

There is a system command execution that is using escalated user permission. With assumption that procTracePID is launched by regular user, it should be handled by same user account without privilege's escalation. There is security concerns if code involve higher permission level.

**Comment by rwxdash** [comment]
Hi @srccn, thanks for opening an issue. We'll investigate the case and try to come up with a solution.

**Comment by srccn** [comment]
A suggestion on repo security. It is better to set up security policy about how team is going to deal with security issues.  ref to https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by rwxdash** [comment]
Hey @srccn, 

Thanks for the suggestion. The process you've mentioned is called with `sudo` and it's necessary to call it with it as the `procTracer` is containing necessary eBPF hooks to collect telemetry data from the system calls. See below:

https://github.com/runforesight/workflow-telemetry-action/blob/917a88f65372dc25bc29fc3abcb3a61e5c57d924/src/processTracer.ts#L72-L88

We'll check and try to set up a security policy for the repository. Marking this issue as closed for now.

**Comment by srccn** [comment]
Thanks for explanation.  OK to close. I mistakenly thought this action dose NOT require runner to have "sudo" permission.
