### ISSUE TITLE
Deprecation warning for Node.js 12 actions

### ISSUE THREAD

**Issue by pakhilov** [runforesight/workflow-telemetry-action#33]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
 
 During a K6 load test on GitHub Actions, an error occurred that said "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: runforesight/workflow-telemetry-action@v1.8.4." This error is due to the deprecation of Node.js 12 for GitHub Actions, as it has been out of support since April 2022. GitHub plans to migrate all actions to run on Node.js 16 by Summer 2023, and in the meantime, they have added a warning to workflows that contain actions running on Node.js 12.

To fix this error, you need to update the action runforesight/workflow-telemetry-action@v1.8.4 to run on Node.js 16. If you are the maintainer of this action, you can update its configuration settings to run on Node.js 16. If you are a user of this action, you need to update your workflow to use the latest version of the action that runs on Node.js 16. You can do this by specifying the version of the action in your workflow using the syntax run: <owner>/<repo>@v<version>.

It is important to take action on this issue as Node.js 12 is no longer supported and using it can result in security vulnerabilities and other issues.

**Comment by rwxdash** [comment]
Hey @pakhilov, thanks for creating the issue. We'll take action as soon as possible.

**Comment by rwxdash** [comment]
Just recalled that we've already upgraded the action to node16 in #23. Seems like we forgot to create a new release. `v1` and `v1.8.5` should now work without any warning regarding the node version. 

Thanks again for reporting, closing the issue.
