### ISSUE TITLE
Gantt chart fails to display if step title has a :

### ISSUE THREAD

**Issue by tspascoal** [runforesight/workflow-telemetry-action#35]
![image](https://user-images.githubusercontent.com/7847935/224052671-48929599-ce8e-4c32-913f-ddf4d5485154.png)

This was the mermaid line that caused the issue

```
	Pull ghcr.io/enricomi/publish-unit-test-result-action:v1.40 : 1678371132000, 167837113600
```

Stripping `:` from step titles should file the problem  (this was not even a regular step, but a pre step installing a docker action)

This is quite common for actions that use docker. The logs for this particular step:

![image](https://user-images.githubusercontent.com/7847935/224053424-a8be4bb7-aa58-4c4b-9d54-e1f38c55a858.png)

**Comment by rwxdash** [comment]
Hey @tspascoal, apologies for the late response.

I'm not certain yet that this issue is directly related to us, but will look into it. Thank you.

**Comment by tspascoal** [comment]
@rwxdash It the way step names are published in the gantt chart.

Sorry I didn't make this clearer.  Here is a simple [repro](https://github.com/tspascoal/workflow-telemetry-action-repro/actions/runs/4520710977)

This is the problematic mermaid gantt chart

```mermaid
gantt
	title build
	dateFormat x
	axisFormat %H:%M:%S
	Set up job : milestone, 1679770574000, 1679770576000
	Pull ghcr.io/enricomi/publish-unit-test-result-action:v1.40 : 1679770576000, 1679770581000
	Collect Workflow Telemetry : 1679770581000, 1679770581000
	Publish Unit Test Results : 1679770583000, 1679770583000
````

I don't see any way to escape `:` in markdown/[mermaid  gant charts](https://mermaid.js.org/syntax/gantt.html)

so to _fix_ this you will probably need to replace `:` in steps with something else

This would be a fix, by cleaning up it up a bit (replaced `:` with a `-`)

```mermaid
gantt
	title build
	dateFormat x
	axisFormat %H:%M:%S
	Set up job : milestone, 1679770574000, 1679770576000
	Pull ghcr.io/enricomi/publish-unit-test-result-action-v1.40 : 1679770576000, 1679770581000
	Collect Workflow Telemetry : 1679770581000, 1679770581000
	Publish Unit Test Results : 1679770583000, 1679770583000
```

The mermaid live editor has the same _problem_

[Issue](https://mermaid.live/edit#pako:eNptkMFqwzAQRH9lEfhmJzZJ41bXltJLIdQtvegi2xtbrSwZedUmhPx7ZSdQB3LbWfbNDnNkla2RcdZIQySMIFKkEUqvdD3KWhI-W9dJgv2o5V4NFx298OiVR8W4LpDA9_BlS-DQKY0DWYMxZJv8Ic_Tu3ydpulMboIcua3XGpq2cgtll2icqmynlr0vtRraxBtFCQWvxOHgNSWyImUN_8kW6zQ8urL7d7_PLu6PVmusCD6t-95p-wvvqLFDcocZPF3fgLfnEPARQgRwIHibQgxzdnXNriaWxazDUJGqQ7FHYQAEozY8FoyHscadDD6CCXMKp9KTLQ6mYpycx5j5fuz8ScnGye68PP0BPaeE9A)

[Fixed](https://mermaid.live/edit#pako:eNptkE9PAjEQxb_KpAk3FpaArPaqMV5MiKvx0kvZnYXR_tm0U4UQvrtdJBESb_Mm83vz8g6i8S0KKTbaMSunmIkNwjqRaQfZasZHH6xm2A1a7yie9ehJjp7lqB7WNTKkHj78GiRYMhjZOxzDbFndVVV5Uy3KsryQyywHbpWMgc22CRPyU3SBGm9p2qe1obgtkiMuOHsVAWMyXOiGybviazZZlPnRld2f--3s7H7vjcGG4d2Hz874b3hFgxY57C_g0_U_8Oo3BLzlEBmMDC-nEPGSnV-z8xMrxsJirojaXOxBOQAleJsfKyHz2GKns48Syh3zqU7s671rhOSQcCxSP3T-QHoTtBWy0ybi8Qe17oUy)

**Comment by tspascoal** [comment]
I've submitted a PR, as I should have done in the first place :)
